# Generated by Django 2.2.5 on 2020-01-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=40)),
                ('Phone', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=40)),
            ],
        ),
    ]
